services:
  - type: web
    name: personal-food-api
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    rootDir: backend
    plan: free
    autoDeploy: true
